%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

%global __cmake_in_source_build 1

Name:           ros-kilted-auto-apms-behavior-tree
Version:        1.4.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS auto_apms_behavior_tree package

License:        Apache-2.0
URL:            https://autoapms.github.io/auto-apms-guide/
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kilted-ament-index-python
Requires:       ros-kilted-auto-apms-behavior-tree-core
Requires:       ros-kilted-auto-apms-interfaces
Requires:       ros-kilted-auto-apms-util
Requires:       ros-kilted-generate-parameter-library
Requires:       ros-kilted-geometry-msgs
Requires:       ros-kilted-rcl-interfaces
Requires:       ros-kilted-rclcpp
Requires:       ros-kilted-rclcpp-action
Requires:       ros-kilted-rclcpp-components
Requires:       ros-kilted-rclpy
Requires:       ros-kilted-ros2cli
Requires:       ros-kilted-ros2param
Requires:       ros-kilted-std-srvs
Requires:       ros-kilted-tf2-geometry-msgs
Requires:       ros-kilted-tinyxml2-vendor
Requires:       ros-kilted-ros-workspace
BuildRequires:  ros-kilted-ament-cmake
BuildRequires:  ros-kilted-ament-cmake-python
BuildRequires:  ros-kilted-ament-index-python
BuildRequires:  ros-kilted-auto-apms-behavior-tree-core
BuildRequires:  ros-kilted-auto-apms-interfaces
BuildRequires:  ros-kilted-auto-apms-util
BuildRequires:  ros-kilted-generate-parameter-library
BuildRequires:  ros-kilted-geometry-msgs
BuildRequires:  ros-kilted-rcl-interfaces
BuildRequires:  ros-kilted-rclcpp
BuildRequires:  ros-kilted-rclcpp-action
BuildRequires:  ros-kilted-rclcpp-components
BuildRequires:  ros-kilted-std-srvs
BuildRequires:  ros-kilted-tf2-geometry-msgs
BuildRequires:  ros-kilted-tinyxml2-vendor
BuildRequires:  ros-kilted-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-kilted-ament-cmake-copyright
%endif

%description
Standard AutoAPMS behavior tree nodes and deployment tools

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/kilted" \
    -DAMENT_PREFIX_PATH="/opt/ros/kilted" \
    -DCMAKE_PREFIX_PATH="/opt/ros/kilted" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/kilted

%changelog
* Fri Jan 30 2026 Robin Müller <mue.robin@icloud.com> - 1.4.0-1
- Autogenerated by Bloom

