%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/rolling/.*$
%global __requires_exclude_from ^/opt/ros/rolling/.*$

Name:           ros-rolling-auto-apms-ros2behavior
Version:        1.5.1
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS auto_apms_ros2behavior package

License:        Apache-2.0
URL:            https://autoapms.github.io/auto-apms-guide/
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-rolling-ament-index-python
Requires:       ros-rolling-auto-apms-behavior-tree
Requires:       ros-rolling-auto-apms-interfaces
Requires:       ros-rolling-rcl-interfaces
Requires:       ros-rolling-rclpy
Requires:       ros-rolling-ros2cli
Requires:       ros-rolling-ros2param
Requires:       ros-rolling-ros2run
Requires:       ros-rolling-std-srvs
Requires:       ros-rolling-ros-workspace
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  ros-rolling-ament-index-python
BuildRequires:  ros-rolling-auto-apms-behavior-tree
BuildRequires:  ros-rolling-auto-apms-interfaces
BuildRequires:  ros-rolling-rcl-interfaces
BuildRequires:  ros-rolling-rclpy
BuildRequires:  ros-rolling-ros-workspace
BuildRequires:  ros-rolling-ros2cli
BuildRequires:  ros-rolling-ros2param
BuildRequires:  ros-rolling-ros2run
BuildRequires:  ros-rolling-std-srvs
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  python%{python3_pkgversion}-pytest
BuildRequires:  ros-rolling-ament-copyright
%endif

%description
AutoAPMS related extensions for the ROS 2 CLI introducing the ros2 behavior
command

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
%py3_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
%py3_install -- --prefix "/opt/ros/rolling"

%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/rolling

%changelog
* Tue Apr 07 2026 Robin Müller <mue.robin@icloud.com> - 1.5.1-1
- Autogenerated by Bloom

* Fri Mar 06 2026 Robin Müller <mue.robin@icloud.com> - 1.5.0-1
- Autogenerated by Bloom

* Tue Feb 03 2026 Robin Müller <mue.robin@icloud.com> - 1.4.2-1
- Autogenerated by Bloom

* Tue Feb 03 2026 Robin Müller <mue.robin@icloud.com> - 1.4.1-1
- Autogenerated by Bloom

* Fri Jan 30 2026 Robin Müller <mue.robin@icloud.com> - 1.4.0-1
- Autogenerated by Bloom

