# Copyright 2025 Robin Müller
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Resolve node manifest references to install paths, generating metadata as needed.
#
# This macro takes a metadata ID and one or more node manifest references (relative file paths or
# resource identities using the '::' delimiter) and resolves them to their corresponding install paths.
# If necessary, it calls auto_apms_behavior_tree_generate_node_metadata to generate new metadata.
#
# After calling this macro, the variable _node_manifest_rel_paths__install will contain the resolved
# install paths (or be empty if no node manifest arguments were provided).
#
# :param _metadata_id: The metadata identifier used for generating or looking up node manifests.
# :type _metadata_id: string
# :param ARGN: One or more relative paths or resource identities of existing node manifests.
# :type ARGN: list of strings
#
# @public
#
macro(auto_apms_behavior_tree_get_node_manifest_install_paths _metadata_id)

  set(_node_manifest_rel_paths__install "") # Empty string if no manifest is given
  if(NOT "${ARGN}" STREQUAL "")

    set(_existing_metadata_ids__build "")
    set(_existing_node_manifest_abs_paths__build "")
    set(_existing_metadata_ids__resources "")
    set(_existing_node_manifest_abs_paths__resources "")

    # Collect metadata generated by this package
    foreach(_tuple ${_AUTO_APMS_BEHAVIOR_TREE_CORE__NODE_MANIFEST_BUILD_INFO})
      string(REPLACE "@" ";" _tuple "${_tuple}")
      list(GET _tuple 0 _id)
      list(GET _tuple 1 _node_manifest_abs_path__build)
      list(APPEND _existing_metadata_ids__build "${PROJECT_NAME}::${_id}")
      list(APPEND _existing_node_manifest_abs_paths__build "${_node_manifest_abs_path__build}")
    endforeach()

    # Collect metadata ids registered by other packages
    ament_index_get_resources(_packages_with_node_manifest_resource "${_AUTO_APMS_BEHAVIOR_TREE_CORE__RESOURCE_TYPE_NAME__NODE_MANIFEST}")
    foreach(_package ${_packages_with_node_manifest_resource})
      # Skip resources installed by this package since we use the build info variable instead
      if("${_package}" STREQUAL "${PROJECT_NAME}")
        continue()
      endif()
      ament_index_get_resource(_content "${_AUTO_APMS_BEHAVIOR_TREE_CORE__RESOURCE_TYPE_NAME__NODE_MANIFEST}" "${_package}")
      string(REPLACE "\n" ";" _content "${_content}")
      foreach(_tuple ${_content})
        string(REPLACE "|" ";" _tuple "${_tuple}")
        list(GET _tuple 0 _id)
        list(GET _tuple 1 _rel_path)
        ament_index_has_resource(_prefix "${_AUTO_APMS_BEHAVIOR_TREE_CORE__RESOURCE_TYPE_NAME__NODE_MANIFEST}" "${_package}")
        list(APPEND _existing_metadata_ids__resources "${_package}::${_id}")
        list(APPEND _existing_node_manifest_abs_paths__resources "${_prefix}/${_rel_path}")
      endforeach()
    endforeach()

    # # # # # # # # #
    #
    # Change the input variables for the auto_apms_behavior_tree_generate_node_metadata macro called later
    # so that we reuse all existing metadata
    #
    set(_generate_metadata_inputs ${ARGN})
    set(_matching_existing_metadata_count 0)
    foreach(_var ${ARGN})
      # Check wether the user provided a metadata id referring to this package or another (Using the '::' delimiter)
      string(FIND "${_var}" "::" _index)
      if("${_index}" GREATER -1)
        # Check if metadata for _var has already been generated by this package
        list(FIND _existing_metadata_ids__build "${_var}" _index)
        if("${_index}" GREATER -1)
          list(GET _existing_node_manifest_abs_paths__build "${_index}" _existing_node_manifest_abs_path)
        else()
          # Check if metadata for _var has been generated by other packages
          list(FIND _existing_metadata_ids__resources "${_var}" _index)
          if("${_index}" GREATER -1)
            list(GET _existing_node_manifest_abs_paths__resources "${_index}" _existing_node_manifest_abs_path)
          else()
            message(
              FATAL_ERROR
              "auto_apms_behavior_tree_get_node_manifest_install_paths(): Metadata ID '${_var}' was provided, but no such resource can be found."
            )
          endif()
        endif()

        # If matching metadata is generated by this package, replace the corresponding item in the inputs
        # with the existing node manifest build path
        list(FIND _generate_metadata_inputs "${_var}" _index)
        list(REMOVE_AT _generate_metadata_inputs "${_index}")
        list(INSERT _generate_metadata_inputs "${_index}" "${_existing_node_manifest_abs_path}")
        math(EXPR _matching_existing_metadata_count "${_matching_existing_metadata_count} + 1")
      else()
        # If the '::' delimiter wasn't used, the user must provide a relative path to an existing node manifest file
        if(NOT EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/${_var}")
          message(
            FATAL_ERROR
            "auto_apms_behavior_tree_get_node_manifest_install_paths(): '${_var}' is interpreted as a relative path to a node manifest, but no such file can be found relative to the current source directory ${CMAKE_CURRENT_SOURCE_DIR}."
          )
        endif()
      endif()
    endforeach()
    #
    # # # # # # # # #

    # Call auto_apms_behavior_tree_generate_node_metadata reusing as much of the existing metadata as possible
    if("${_matching_existing_metadata_count}" EQUAL 0)
      # We cannot use any existing node manifests and must generate everything
      auto_apms_behavior_tree_generate_node_metadata("${_metadata_id}" ${ARGN})

      # Sticking to the default manifest install file path used by the macro above for the resource info
      set(_node_manifest_rel_paths__install "${_AUTO_APMS_BEHAVIOR_TREE_CORE__RESOURCE_DIR_RELATIVE__METADATA}/node_manifest_${_metadata_id}.yaml")
    else()
      list(LENGTH _generate_metadata_inputs _generate_metadata_inputs_length)
      if("${_generate_metadata_inputs_length}" EQUAL "${_matching_existing_metadata_count}")
        # We don't have to generate anything because all required node manifests have already been generated.
        foreach(_node_manifest_path ${_generate_metadata_inputs})
          if("${_node_manifest_path}" IN_LIST _existing_node_manifest_abs_paths__build)
            # Regarding the manifests generated by this package, there will be corresponding install paths and we just have to forward those.
            get_filename_component(_file_name "${_node_manifest_path}" NAME)
            list(APPEND _node_manifest_rel_paths__install "${_AUTO_APMS_BEHAVIOR_TREE_CORE__RESOURCE_DIR_RELATIVE__METADATA}/${_file_name}")
          else()
            # Regarding the manifests generated by other package, we use the existing absolute manifest install paths.
            list(APPEND _node_manifest_rel_paths__install "${_node_manifest_path}")
          endif()
        endforeach()
      else()
        # There are some already registered node manifests (looked up using the provided metadata ID(s)) but we also have to generate additional metadata. So we look up the existing node manifest files and use them to generate the metadata under a new ID.
        auto_apms_behavior_tree_generate_node_metadata("${_metadata_id}" ${_generate_metadata_inputs})

        # Sticking to the default manifest install file path used by the macro above for the resource info
        set(_node_manifest_rel_paths__install "${_AUTO_APMS_BEHAVIOR_TREE_CORE__RESOURCE_DIR_RELATIVE__METADATA}/node_manifest_${_metadata_id}.yaml")
      endif()
    endif()
  endif()

endmacro()
